### PR TITLE
Release the lock if migration fails. fixes #47

### LINKED ISSUE #47: Library does not release the lock if cluster is unhealthy
What happens:

Node acquires the lock
Starts SchemaLoader to do the migration
Schema loader checks cluster health which says "unhealthy"
Library throws an error and lock hangs there forever
Logs:

```
[2016-12-21 11:37:18,003] INFO  [main] u.s.c.Lock - [] Attempting to acquire lock for 'app.schema_migration', using client id '047b5b3c-ee9e-4059-b083-3a6bcd7e9259'
[2016-12-21 11:37:18,079] INFO  [main] u.s.c.CqlMigratorImpl - [] Loading cql files from [/tmp/cqlmigrate5345071027669587170]
[2016-12-21 11:37:18,093] INFO  [main] u.s.c.KeyspaceBootstrapper - [] Keyspace found, not applying bootstrap.cql
Exception in thread "main" uk.sky.cqlmigrate.exception.ClusterUnhealthyException: Cluster not healthy, the following hosts are down: [***]
        at uk.sky.cqlmigrate.ClusterHealth.check(ClusterHealth.java:28)
        at uk.sky.cqlmigrate.SessionContext.checkClusterHealth(SessionContext.java:35)
        at uk.sky.cqlmigrate.CqlLoader.load(CqlLoader.java:18)
        at uk.sky.cqlmigrate.SchemaLoader$Loader.apply(SchemaLoader.java:45)
        at uk.sky.cqlmigrate.CqlPaths.lambda$applyInSortedOrder$7(CqlPaths.java:49)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at uk.sky.cqlmigrate.CqlPaths.applyInSortedOrder(CqlPaths.java:49)
        at uk.sky.cqlmigrate.SchemaLoader.load(SchemaLoader.java:28)
        at uk.sky.cqlmigrate.CqlMigratorImpl.migrate(CqlMigratorImpl.java:90)
        at uk.sky.cqlmigrate.initializer.CqlMigrateInitializer.migrate(CqlMigrateInitializer.java:80)
        at uk.sky.cqlmigrate.initializer.CqlMigrateBundle.cqlMigrate(CqlMigrateBundle.java:62)
        at uk.sky.cqlmigrate.initializer.CqlMigrateBundle.run(CqlMigrateBundle.java:39)
        at uk.sky.cqlmigrate.initializer.CqlMigrateBundle.run(CqlMigrateBundle.java:15)
        at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
        at io.dropwizard.cli.Cli.run(Cli.java:75)
        at io.dropwizard.Application.run(Application.java:79)
        at com.bskyb.App.main(App.java:54)
Registered app server agent with Node ID[9579] Component ID[1980] Application ID [68]
```

### PR DESCRIPTION
**Pull request by v-boiko**
Fix for #47

### CODE REVIEW

File: src/test/java/uk/sky/cqlmigrate/CqlMigratorImplTest.java [hunk 1]
```diff
@@ -152,13 +152,29 @@ public void shouldRemoveLockAfterMigration() throws Exception {
...
+
+        //when
+        try {
+            MIGRATOR.migrate(CASSANDRA_HOSTS, binaryPort, username, password, TEST_KEYSPACE, cqlPaths);
+        } catch (RuntimeException ignore) {
+        }
+
+        //then
+        ResultSet resultSet = session.execute("SELECT * FROM cqlmigrate.locks WHERE name = ?", LOCK_NAME);
+        assertThat(resultSet.isExhausted()).as("Is lock released").isTrue();
```
Comment (v-boiko) [inline src/test/java/uk/sky/cqlmigrate/CqlMigratorImplTest.java]: In our case, we don't proceed with deployment of the second node, if the first node fails. In that case, the failure of the deployment is already a matter for investigation, so we don't need another manual action to do something if the problem is explained in logs, giving us a hint to check the database.

So, maybe it needs to be configurable?

Comment (charlie-mcneill) [inline src/test/java/uk/sky/cqlmigrate/CqlMigratorImplTest.java]: I am a fan of configurable. This makes a lot of sense in your situation :) 👍

**Comment by charlie-mcneill** [comment]
Looks good to me, probably worth one more set of eyes. Also maybe just a little bit of information in README? @adamdougal would you be able to take a final look?

File: src/main/java/uk/sky/cqlmigrate/Lock.java [hunk 2]
```diff
@@ -16,6 +16,7 @@
 
     private final LockingMechanism lockingMechanism;
     private final LockConfig lockConfig;
+    private boolean errorHappened;
```
Comment (adamdougal) [inline src/main/java/uk/sky/cqlmigrate/Lock.java]: Would prefer it if we could keep this class immutable. Could potentially pass a boolean into the `unlock` method to indicate whether or not an error occurred and then call it at the end of the `try` and in the `catch` block.

File: src/main/java/uk/sky/cqlmigrate/LockConfig.java [hunk 3]
```diff
@@ -26,6 +28,10 @@ String getClientId() {
         return clientId;
     }
 
+    public boolean getUnlockOnFailure() {
```
Comment (adamdougal) [inline src/main/java/uk/sky/cqlmigrate/LockConfig.java]: This would probably read better without the `get` at the start.

File: src/main/java/uk/sky/cqlmigrate/LockConfig.java [hunk 4]
```diff
@@ -68,8 +75,18 @@ public LockConfigBuilder withTimeout(Duration timeout) {
             return this;
         }
 
+        /**
+         * Release the lock in case of failure
```
Comment (adamdougal) [inline src/main/java/uk/sky/cqlmigrate/LockConfig.java]: This implies that the default behaviour is that it wont release the lock on failure. But maybe it's worth adding it here explicitly and saying why that's default?

File: src/main/java/uk/sky/cqlmigrate/Lock.java (hunk 2 above)
Comment (v-boiko) [inline src/main/java/uk/sky/cqlmigrate/Lock.java]: ok, I just thought to hide the stuff inside and make it 'lighter' from the top-level, but this can work as well, thanks

File: src/main/java/uk/sky/cqlmigrate/LockConfig.java (hunk 3 above)
Comment (v-boiko) [inline src/main/java/uk/sky/cqlmigrate/LockConfig.java]: agree, had doubts though readability vs conventions. thanks for backing readability! 😄

File: src/main/java/uk/sky/cqlmigrate/LockConfig.java (hunk 4 above)
Comment (v-boiko) [inline src/main/java/uk/sky/cqlmigrate/LockConfig.java]: yeah, will do

**Comment by adamdougal** [comment]
LGTM, @charlie-mcneill are you happy to merge this?

**Comment by charlie-mcneill** [comment]
LGTM! 👍
